

[run]
fix_hull = true
refine_poly = true
rm_crossing = true

[img]
# Controls the dimentions of the output image
width  = 1000
height = 1000
# Controls buffer around edfe of scree;
# larger -> more space
edge_buffer = 1.5


[draw]
# Toggles drawing of various things
axis = true
points = true
polygon = true
blob = true
background = true
labels = true
fontsize = 20.0
# Sizes of things
point_radius = 3.0
polygon_thickness = 1.6
axis_thickness = 0.6


[b2]
mindist_radius_factor = 3.0
refine_epsilon = 1.0
