

[run]
fix_hull = true
refine_poly = true
rm_crossing = true

[img]
# Controls the dimentions of the output image
width  = 600
height = 600
# Controls buffer around edfe of scree;
# larger -> more space
edge_buffer = 1.5


[draw]
# Toggles drawing of various things
axis = false
points = true
polygon = true
blob = true
background = true
# Sizes of things
point_radius = 2.0
polygon_thickness = 0.6
axis_thickness = 0.6


[b2]
mindist_radius_factor = 3.0
refine_epsilon = 1.0
